window.FISHKILLER_SCENARIOS = (window.FISHKILLER_SCENARIOS || []).concat([
  {
    id: "hu-open-a5s",
    tableSize: "hu",
    pack: "100bb Cash",
    title: "Attack the unopened blind",
    copy: "Folded to you heads-up. With wheel coverage and suited playability, this hand wants initiative.",
    heroHand: "A5s",
    heroSeat: "SB / BTN",
    difficulty: "Core",
    xp: 18,
    facts: [
      { label: "Hero Seat", value: "SB / BTN" },
      { label: "Pot Type", value: "Unopened" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Open 2.5x", "Open Jam"],
    correctAction: "Open 2.5x",
    explanation: "A5s is a comfortable heads-up open because it carries blocker power, wheel equity, and clean postflop playability.",
    actors: [{ seat: "SB / BTN", label: "Hero" }],
  },
  {
    id: "hu-defend-k9s",
    tableSize: "hu",
    pack: "100bb Cash",
    title: "Defend wide with playable suited kings",
    copy: "Button opens and you are closing the action in the big blind. This combo realizes well without needing to bloat the pot.",
    heroHand: "K9s",
    heroSeat: "BB",
    difficulty: "Core",
    xp: 18,
    facts: [
      { label: "Hero Seat", value: "BB" },
      { label: "Villain", value: "SB / BTN opens 2.5x" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Call", "3-bet to 10bb"],
    correctAction: "Call",
    explanation: "K9s keeps enough showdown value and suited realization to defend profitably as a call.",
    actors: [
      { seat: "SB / BTN", label: "Opens" },
      { seat: "BB", label: "Hero" },
    ],
  },
  {
    id: "hu-3bet-ajo",
    tableSize: "hu",
    pack: "100bb Cash",
    title: "Punish opens with a strong offsuit ace",
    copy: "The button opens and your hand is strong enough to pull value from wider continuing ranges.",
    heroHand: "AJo",
    heroSeat: "BB",
    difficulty: "Sharp",
    xp: 24,
    facts: [
      { label: "Hero Seat", value: "BB" },
      { label: "Villain", value: "SB / BTN opens 2.5x" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Call", "3-bet to 10bb"],
    correctAction: "3-bet to 10bb",
    explanation: "AJo performs best by taking the aggressive branch against the extremely wide heads-up opening range.",
    actors: [
      { seat: "SB / BTN", label: "Opens" },
      { seat: "BB", label: "Hero" },
    ],
  },
  {
    id: "hu-4bet-ako",
    tableSize: "hu",
    pack: "100bb Cash",
    title: "Continue pressuring with premium blockers",
    copy: "You opened, got 3-bet, and now hold a hand that comfortably sits in the value-heavy 4-bet lane.",
    heroHand: "AKo",
    heroSeat: "SB / BTN",
    difficulty: "Solver",
    xp: 30,
    facts: [
      { label: "Hero Seat", value: "SB / BTN" },
      { label: "Pot Type", value: "Raised then 3-bet" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Call", "4-bet to 22bb"],
    correctAction: "4-bet to 22bb",
    explanation: "AKo wants to leverage its blockers and strong equity by 4-betting rather than letting the big blind realize cleanly.",
    actors: [
      { seat: "SB / BTN", label: "Hero" },
      { seat: "BB", label: "3-bets" },
    ],
  },
  {
    id: "hu-fold-74o",
    tableSize: "hu",
    pack: "100bb Cash",
    title: "Let the rough offsuit trash go",
    copy: "You are getting a defend price, but not every offsuit combo is worth continuing with.",
    heroHand: "74o",
    heroSeat: "BB",
    difficulty: "Core",
    xp: 18,
    facts: [
      { label: "Hero Seat", value: "BB" },
      { label: "Villain", value: "SB / BTN opens 2.5x" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Call", "3-bet to 10bb"],
    correctAction: "Fold",
    explanation: "74o is too disconnected and dominated to defend profitably even against wide heads-up pressure.",
    actors: [
      { seat: "SB / BTN", label: "Opens" },
      { seat: "BB", label: "Hero" },
    ],
  },
  {
    id: "hu-defend-q8s",
    tableSize: "hu",
    pack: "100bb Cash",
    title: "Take the passive defend with suited queens",
    copy: "This is a classic wide defend that plays well enough postflop without needing to force a 3-bet.",
    heroHand: "Q8s",
    heroSeat: "BB",
    difficulty: "Core",
    xp: 18,
    facts: [
      { label: "Hero Seat", value: "BB" },
      { label: "Villain", value: "SB / BTN opens 2.5x" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Call", "3-bet to 10bb"],
    correctAction: "Call",
    explanation: "Q8s retains solid equity realization and enough domination upside to defend as a call.",
    actors: [
      { seat: "SB / BTN", label: "Opens" },
      { seat: "BB", label: "Hero" },
    ],
  },
  {
    id: "hu-open-j7s",
    tableSize: "hu",
    pack: "100bb Cash",
    title: "Stay aggressive from the button",
    copy: "Short-handed play rewards initiative. This suited jack is too lively to leave behind unopened.",
    heroHand: "J7s",
    heroSeat: "SB / BTN",
    difficulty: "Core",
    xp: 18,
    facts: [
      { label: "Hero Seat", value: "SB / BTN" },
      { label: "Pot Type", value: "Unopened" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Open 2.5x", "Open Jam"],
    correctAction: "Open 2.5x",
    explanation: "J7s is comfortably inside the heads-up opening range and benefits from taking the first aggressive action.",
    actors: [{ seat: "SB / BTN", label: "Hero" }],
  },
  {
    id: "hu-defend-55",
    tableSize: "hu",
    pack: "100bb Cash",
    title: "Set-mine and realize with the pair",
    copy: "Against a heads-up open, low pocket pairs do not need to inflate the pot to stay profitable.",
    heroHand: "55",
    heroSeat: "BB",
    difficulty: "Core",
    xp: 18,
    facts: [
      { label: "Hero Seat", value: "BB" },
      { label: "Villain", value: "SB / BTN opens 2.5x" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Call", "3-bet to 10bb"],
    correctAction: "Call",
    explanation: "55 is strong enough to continue, but calling keeps in dominated holdings while preserving postflop flexibility.",
    actors: [
      { seat: "SB / BTN", label: "Opens" },
      { seat: "BB", label: "Hero" },
    ],
  },
  {
    id: "hu-3bet-a5o",
    tableSize: "hu",
    pack: "100bb Cash",
    title: "Use blockers to fight back",
    copy: "You are in the big blind with a blocker-heavy ace that works naturally inside the aggressive bucket.",
    heroHand: "A5o",
    heroSeat: "BB",
    difficulty: "Sharp",
    xp: 24,
    facts: [
      { label: "Hero Seat", value: "BB" },
      { label: "Villain", value: "SB / BTN opens 2.5x" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Call", "3-bet to 10bb"],
    correctAction: "3-bet to 10bb",
    explanation: "A5o benefits from blocker pressure and prefers denying realization to the opener rather than flatting offsuit.",
    actors: [
      { seat: "SB / BTN", label: "Opens" },
      { seat: "BB", label: "Hero" },
    ],
  },
  {
    id: "hu-4bet-qq",
    tableSize: "hu",
    pack: "100bb Cash",
    title: "Keep the premium branch simple",
    copy: "You opened and faced a 3-bet. This hand is not interested in a passive response.",
    heroHand: "QQ",
    heroSeat: "SB / BTN",
    difficulty: "Solver",
    xp: 30,
    facts: [
      { label: "Hero Seat", value: "SB / BTN" },
      { label: "Pot Type", value: "Raised then 3-bet" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Call", "4-bet to 22bb"],
    correctAction: "4-bet to 22bb",
    explanation: "QQ belongs in the value-rich 4-betting region and should keep applying pressure before the flop.",
    actors: [
      { seat: "SB / BTN", label: "Hero" },
      { seat: "BB", label: "3-bets" },
    ],
  },
]);
