window.FISHKILLER_SCENARIOS = (window.FISHKILLER_SCENARIOS || []).concat([
  {
    id: "9m-open-aqs-utg",
    tableSize: "nine",
    pack: "100bb Cash",
    title: "Anchor the full-ring UTG range correctly",
    copy: "In full ring, early opening ranges tighten sharply, but premium suited broadways remain a clean raise.",
    heroHand: "AQs",
    heroSeat: "UTG",
    difficulty: "Core",
    xp: 18,
    facts: [
      { label: "Hero Seat", value: "UTG" },
      { label: "Pot Type", value: "Unopened" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Open 2.2x", "Open Jam"],
    correctAction: "Open 2.2x",
    explanation: "AQs has enough raw strength and blocker value to sit firmly inside a disciplined UTG range full ring.",
    actors: [{ seat: "UTG", label: "Hero" }],
  },
  {
    id: "9m-fold-ato-utg",
    tableSize: "nine",
    pack: "100bb Cash",
    title: "Avoid the early-position offsuit trap",
    copy: "This hand looks playable, but full-ring UTG demands much more robust domination properties.",
    heroHand: "ATo",
    heroSeat: "UTG",
    difficulty: "Core",
    xp: 18,
    facts: [
      { label: "Hero Seat", value: "UTG" },
      { label: "Pot Type", value: "Unopened" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Open 2.2x", "Open Jam"],
    correctAction: "Fold",
    explanation: "ATo is too dominated and too exposed to stronger continuing ranges to open from UTG in 9-max.",
    actors: [{ seat: "UTG", label: "Hero" }],
  },
  {
    id: "9m-open-55-mp",
    tableSize: "nine",
    pack: "100bb Cash",
    title: "Open the pair from middle position",
    copy: "With several seats behind but plenty of playability, this pocket pair still wants to raise first in.",
    heroHand: "55",
    heroSeat: "MP",
    difficulty: "Core",
    xp: 18,
    facts: [
      { label: "Hero Seat", value: "MP" },
      { label: "Pot Type", value: "Unopened" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Open 2.2x", "Open Jam"],
    correctAction: "Open 2.2x",
    explanation: "55 retains enough equity and set value to open comfortably from middle position full ring.",
    actors: [{ seat: "MP", label: "Hero" }],
  },
  {
    id: "9m-open-kjs-lj",
    tableSize: "nine",
    pack: "100bb Cash",
    title: "Loosen correctly in the lojack",
    copy: "Once you reach the lojack, suited broadways begin opening more cleanly for value and pressure.",
    heroHand: "KJs",
    heroSeat: "LJ",
    difficulty: "Core",
    xp: 18,
    facts: [
      { label: "Hero Seat", value: "LJ" },
      { label: "Pot Type", value: "Unopened" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Open 2.2x", "Open Jam"],
    correctAction: "Open 2.2x",
    explanation: "KJs is high enough in the full-ring lojack range to raise first in and leverage good board coverage.",
    actors: [{ seat: "LJ", label: "Hero" }],
  },
  {
    id: "9m-hj-3bet-jj-vs-utg",
    tableSize: "nine",
    pack: "100bb Cash",
    title: "Value 3-bet jacks versus the earliest seat",
    copy: "UTG opens and jacks are strong enough to build the pot before flatter-heavy branches form behind you.",
    heroHand: "JJ",
    heroSeat: "HJ",
    difficulty: "Solver",
    xp: 30,
    facts: [
      { label: "Hero Seat", value: "HJ" },
      { label: "Villain", value: "UTG opens 2.2x" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Call", "3-bet to 9bb"],
    correctAction: "3-bet to 9bb",
    explanation: "JJ performs best as a value 3-bet that denies multiway equity and pressures the early opening range.",
    actors: [
      { seat: "UTG", label: "Opens" },
      { seat: "HJ", label: "Hero" },
    ],
  },
  {
    id: "9m-co-call-kjs-vs-hj",
    tableSize: "nine",
    pack: "100bb Cash",
    title: "Take the in-position flat with suited broadway",
    copy: "Hijack opens and your cutoff seat can realize beautifully with this suited broadway without needing a 3-bet.",
    heroHand: "KJs",
    heroSeat: "CO",
    difficulty: "Sharp",
    xp: 24,
    facts: [
      { label: "Hero Seat", value: "CO" },
      { label: "Villain", value: "HJ opens 2.2x" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Call", "3-bet to 9.5bb"],
    correctAction: "Call",
    explanation: "KJs realizes well in position and keeps dominated suited broadways in the hijack range.",
    actors: [
      { seat: "HJ", label: "Opens" },
      { seat: "CO", label: "Hero" },
    ],
  },
  {
    id: "9m-btn-3bet-a5s-vs-co",
    tableSize: "nine",
    pack: "100bb Cash",
    title: "Use the button to pressure cutoff opens",
    copy: "Cutoff ranges are wide enough that suited wheel aces become excellent light 3-bets in position.",
    heroHand: "A5s",
    heroSeat: "BTN",
    difficulty: "Solver",
    xp: 30,
    facts: [
      { label: "Hero Seat", value: "BTN" },
      { label: "Villain", value: "CO opens 2.2x" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Call", "3-bet to 9.5bb"],
    correctAction: "3-bet to 9.5bb",
    explanation: "A5s gains from blocker leverage and keeps enough playability when called to prefer the aggressive route.",
    actors: [
      { seat: "CO", label: "Opens" },
      { seat: "BTN", label: "Hero" },
    ],
  },
  {
    id: "9m-bb-call-t8s-vs-btn",
    tableSize: "nine",
    pack: "100bb Cash",
    title: "Defend suited connectors versus the button",
    copy: "Button opens wide and your suited connector closes the action with enough playability to continue.",
    heroHand: "T8s",
    heroSeat: "BB",
    difficulty: "Core",
    xp: 18,
    facts: [
      { label: "Hero Seat", value: "BB" },
      { label: "Villain", value: "BTN opens 2.2x" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Call", "3-bet to 9.5bb"],
    correctAction: "Call",
    explanation: "T8s realizes well enough against the wide button range to profit as a defend.",
    actors: [
      { seat: "BTN", label: "Opens" },
      { seat: "BB", label: "Hero" },
    ],
  },
  {
    id: "9m-sb-3bet-aqo-vs-lj",
    tableSize: "nine",
    pack: "100bb Cash",
    title: "Prefer the value 3-bet from the small blind",
    copy: "Lojack opens and this strong offsuit ace does not want to flat routinely out of position.",
    heroHand: "AQo",
    heroSeat: "SB",
    difficulty: "Sharp",
    xp: 24,
    facts: [
      { label: "Hero Seat", value: "SB" },
      { label: "Villain", value: "LJ opens 2.2x" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Call", "3-bet to 11bb"],
    correctAction: "3-bet to 11bb",
    explanation: "AQo wants to drive value and deny the lojack clean realization when forced to play out of position.",
    actors: [
      { seat: "LJ", label: "Opens" },
      { seat: "SB", label: "Hero" },
    ],
  },
  {
    id: "9m-fold-kqo-bb-vs-utg",
    tableSize: "nine",
    pack: "100bb Cash",
    title: "Respect UTG strength from the big blind",
    copy: "The opening range is tight and this attractive-looking offsuit broadway does not realize well enough to continue.",
    heroHand: "KQo",
    heroSeat: "BB",
    difficulty: "Sharp",
    xp: 24,
    facts: [
      { label: "Hero Seat", value: "BB" },
      { label: "Villain", value: "UTG opens 2.2x" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Call", "3-bet to 9.5bb"],
    correctAction: "Fold",
    explanation: "KQo runs into too much domination against UTG and lacks clean realization from the blinds.",
    actors: [
      { seat: "UTG", label: "Opens" },
      { seat: "BB", label: "Hero" },
    ],
  },
]);
