window.FISHKILLER_SCENARIOS = (window.FISHKILLER_SCENARIOS || []).concat([
  {
    id: "6m-open-aqs-utg",
    tableSize: "six",
    pack: "100bb Cash",
    title: "Open premium suited broadways up front",
    copy: "Six-max opening ranges begin tighter in early position, but this hand remains a clear value open.",
    heroHand: "AQs",
    heroSeat: "UTG",
    difficulty: "Core",
    xp: 18,
    facts: [
      { label: "Hero Seat", value: "UTG" },
      { label: "Pot Type", value: "Unopened" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Open 2.3x", "Open Jam"],
    correctAction: "Open 2.3x",
    explanation: "AQs is comfortably strong enough to anchor part of the UTG opening range in 6-max cash.",
    actors: [{ seat: "UTG", label: "Hero" }],
  },
  {
    id: "6m-fold-kto-utg",
    tableSize: "six",
    pack: "100bb Cash",
    title: "Do not leak from early position",
    copy: "This offsuit broadway looks pretty, but it lacks the robustness needed for the tightest opening seat.",
    heroHand: "KTo",
    heroSeat: "UTG",
    difficulty: "Core",
    xp: 18,
    facts: [
      { label: "Hero Seat", value: "UTG" },
      { label: "Pot Type", value: "Unopened" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Open 2.3x", "Open Jam"],
    correctAction: "Fold",
    explanation: "KTo is too dominated and too vulnerable to continue from UTG in a disciplined 6-max baseline.",
    actors: [{ seat: "UTG", label: "Hero" }],
  },
  {
    id: "6m-open-99-hj",
    tableSize: "six",
    pack: "100bb Cash",
    title: "Open middle pairs from the hijack",
    copy: "You are clear of the earliest seat and holding a pair that wants to grow the pot preflop.",
    heroHand: "99",
    heroSeat: "HJ",
    difficulty: "Core",
    xp: 18,
    facts: [
      { label: "Hero Seat", value: "HJ" },
      { label: "Pot Type", value: "Unopened" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Open 2.3x", "Open Jam"],
    correctAction: "Open 2.3x",
    explanation: "99 is a comfortable open from the hijack thanks to raw equity, board coverage, and set value.",
    actors: [{ seat: "HJ", label: "Hero" }],
  },
  {
    id: "6m-open-ato-co",
    tableSize: "six",
    pack: "100bb Cash",
    title: "Open broadway strength from the cutoff",
    copy: "The cutoff can widen meaningfully, and this hand is strong enough to attack the blinds.",
    heroHand: "ATo",
    heroSeat: "CO",
    difficulty: "Core",
    xp: 18,
    facts: [
      { label: "Hero Seat", value: "CO" },
      { label: "Pot Type", value: "Unopened" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Open 2.3x", "Open Jam"],
    correctAction: "Open 2.3x",
    explanation: "ATo is high enough in the cutoff tree to open for value and position advantage.",
    actors: [{ seat: "CO", label: "Hero" }],
  },
  {
    id: "6m-open-54s-btn",
    tableSize: "six",
    pack: "100bb Cash",
    title: "Use position to open connected suited junk",
    copy: "The button gets to realize position and pressure. This suited connector belongs in the raise-first bucket.",
    heroHand: "54s",
    heroSeat: "BTN",
    difficulty: "Core",
    xp: 18,
    facts: [
      { label: "Hero Seat", value: "BTN" },
      { label: "Pot Type", value: "Unopened" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Open 2.3x", "Open Jam"],
    correctAction: "Open 2.3x",
    explanation: "54s earns its keep by leveraging button position and excellent nutted coverage against the blinds.",
    actors: [{ seat: "BTN", label: "Hero" }],
  },
  {
    id: "6m-fold-ajo-co-vs-utg",
    tableSize: "six",
    pack: "100bb Cash",
    title: "Respect the UTG opening range",
    copy: "An early-position raise narrows the value region quickly, and this offsuit ace becomes a fold in the cutoff.",
    heroHand: "AJo",
    heroSeat: "CO",
    difficulty: "Sharp",
    xp: 24,
    facts: [
      { label: "Hero Seat", value: "CO" },
      { label: "Villain", value: "UTG opens 2.3x" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Call", "3-bet to 9.5bb"],
    correctAction: "Fold",
    explanation: "AJo suffers badly against a tight UTG range and does not realize cleanly enough to continue.",
    actors: [
      { seat: "UTG", label: "Opens" },
      { seat: "CO", label: "Hero" },
    ],
  },
  {
    id: "6m-call-76s-btn-vs-hj",
    tableSize: "six",
    pack: "100bb Cash",
    title: "Flat in position with suited connectivity",
    copy: "The hijack opens and you are on the button with a hand that plays beautifully postflop.",
    heroHand: "76s",
    heroSeat: "BTN",
    difficulty: "Sharp",
    xp: 24,
    facts: [
      { label: "Hero Seat", value: "BTN" },
      { label: "Villain", value: "HJ opens 2.3x" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Call", "3-bet to 9.5bb"],
    correctAction: "Call",
    explanation: "76s likes the in-position flat because it realizes well and keeps dominated high-card bluffs around.",
    actors: [
      { seat: "HJ", label: "Opens" },
      { seat: "BTN", label: "Hero" },
    ],
  },
  {
    id: "6m-sb-3bet-aqs-vs-co",
    tableSize: "six",
    pack: "100bb Cash",
    title: "Squeeze value from the small blind",
    copy: "Cutoff opens and your hand is too strong to flatten routinely out of position.",
    heroHand: "AQs",
    heroSeat: "SB",
    difficulty: "Sharp",
    xp: 24,
    facts: [
      { label: "Hero Seat", value: "SB" },
      { label: "Villain", value: "CO opens 2.3x" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Call", "3-bet to 11bb"],
    correctAction: "3-bet to 11bb",
    explanation: "AQs wants to press value and deny realization from a broad cutoff opening range.",
    actors: [
      { seat: "CO", label: "Opens" },
      { seat: "SB", label: "Hero" },
    ],
  },
  {
    id: "6m-bb-3bet-a5s-vs-btn",
    tableSize: "six",
    pack: "100bb Cash",
    title: "Lean on suited wheel blockers from the big blind",
    copy: "Button opens wide enough that this suited ace can profitably upgrade from call to 3-bet.",
    heroHand: "A5s",
    heroSeat: "BB",
    difficulty: "Sharp",
    xp: 24,
    facts: [
      { label: "Hero Seat", value: "BB" },
      { label: "Villain", value: "BTN opens 2.3x" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Call", "3-bet to 10bb"],
    correctAction: "3-bet to 10bb",
    explanation: "A5s combines blocker leverage with enough equity when called to make a very natural 3-bet.",
    actors: [
      { seat: "BTN", label: "Opens" },
      { seat: "BB", label: "Hero" },
    ],
  },
  {
    id: "6m-hj-3bet-qq-vs-utg",
    tableSize: "six",
    pack: "100bb Cash",
    title: "Do not trap queens versus early opens",
    copy: "UTG opens and this pair belongs in your value-heavy 3-betting region immediately.",
    heroHand: "QQ",
    heroSeat: "HJ",
    difficulty: "Solver",
    xp: 30,
    facts: [
      { label: "Hero Seat", value: "HJ" },
      { label: "Villain", value: "UTG opens 2.3x" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Call", "3-bet to 9bb"],
    correctAction: "3-bet to 9bb",
    explanation: "QQ is far too strong to flatten versus UTG and prefers extracting value while denying multiway outcomes.",
    actors: [
      { seat: "UTG", label: "Opens" },
      { seat: "HJ", label: "Hero" },
    ],
  },
]);
