window.FISHKILLER_SCENARIOS = (window.FISHKILLER_SCENARIOS || []).concat([
  {
    id: "3m-open-kjo",
    tableSize: "three",
    pack: "100bb Cash",
    title: "Open broadways from the button",
    copy: "Three-handed ranges are wide enough that this offsuit broadway should attack the blinds.",
    heroHand: "KJo",
    heroSeat: "BTN",
    difficulty: "Core",
    xp: 18,
    facts: [
      { label: "Hero Seat", value: "BTN" },
      { label: "Pot Type", value: "Unopened" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Open 2.3x", "Open Jam"],
    correctAction: "Open 2.3x",
    explanation: "KJo is a comfortable button open three-handed because it dominates enough of the blind continues.",
    actors: [{ seat: "BTN", label: "Hero" }],
  },
  {
    id: "3m-sb-3bet-a5o",
    tableSize: "three",
    pack: "100bb Cash",
    title: "Use the blocker 3-bet from the small blind",
    copy: "Button opens and your small blind is the natural place to fight back with blocker-heavy offsuit aces.",
    heroHand: "A5o",
    heroSeat: "SB",
    difficulty: "Sharp",
    xp: 24,
    facts: [
      { label: "Hero Seat", value: "SB" },
      { label: "Villain", value: "BTN opens 2.3x" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Call", "3-bet to 11bb"],
    correctAction: "3-bet to 11bb",
    explanation: "A5o carries strong blocker utility and plays best by contesting initiative instead of flatting out of position.",
    actors: [
      { seat: "BTN", label: "Opens" },
      { seat: "SB", label: "Hero" },
    ],
  },
  {
    id: "3m-bb-defend-87s",
    tableSize: "three",
    pack: "100bb Cash",
    title: "Defend suited connectors in the big blind",
    copy: "The button opens and you are closing the action with a hand that realizes smoothly postflop.",
    heroHand: "87s",
    heroSeat: "BB",
    difficulty: "Core",
    xp: 18,
    facts: [
      { label: "Hero Seat", value: "BB" },
      { label: "Villain", value: "BTN opens 2.3x" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Call", "3-bet to 10.5bb"],
    correctAction: "Call",
    explanation: "87s is an easy defend because it has strong realization and enough nutted coverage without forcing a 3-bet.",
    actors: [
      { seat: "BTN", label: "Opens" },
      { seat: "BB", label: "Hero" },
    ],
  },
  {
    id: "3m-btn-4bet-qq",
    tableSize: "three",
    pack: "100bb Cash",
    title: "Keep queens in the aggressive branch",
    copy: "You opened the button and the small blind 3-bet. This premium pair does not want to underplay the tree.",
    heroHand: "QQ",
    heroSeat: "BTN",
    difficulty: "Solver",
    xp: 30,
    facts: [
      { label: "Hero Seat", value: "BTN" },
      { label: "Pot Type", value: "Raised then 3-bet" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Call", "4-bet to 24bb"],
    correctAction: "4-bet to 24bb",
    explanation: "QQ is a value-forward continue and wants to reclaim initiative before the flop.",
    actors: [
      { seat: "BTN", label: "Hero" },
      { seat: "SB", label: "3-bets" },
    ],
  },
  {
    id: "3m-sb-open-44",
    tableSize: "three",
    pack: "100bb Cash",
    title: "Open wide when folded to the small blind",
    copy: "Button folded. You are now effectively heads-up against the big blind with a pair that wants to play for a raise.",
    heroHand: "44",
    heroSeat: "SB",
    difficulty: "Core",
    xp: 18,
    facts: [
      { label: "Hero Seat", value: "SB" },
      { label: "Pot Type", value: "Folded to SB" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Open 3x", "Open Jam"],
    correctAction: "Open 3x",
    explanation: "44 is far too strong to surrender blind versus blind and prefers raising rather than limping in this trainer pack.",
    actors: [{ seat: "SB", label: "Hero" }],
  },
  {
    id: "3m-bb-3bet-kqo",
    tableSize: "three",
    pack: "100bb Cash",
    title: "Punish the small blind with domination value",
    copy: "Small blind opens into the big blind and this broadway offsuit hand can push equity and initiative hard.",
    heroHand: "KQo",
    heroSeat: "BB",
    difficulty: "Sharp",
    xp: 24,
    facts: [
      { label: "Hero Seat", value: "BB" },
      { label: "Villain", value: "SB opens 3x" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Call", "3-bet to 12bb"],
    correctAction: "3-bet to 12bb",
    explanation: "KQo gains from isolating the blind-versus-blind opener and denying easy realization to weaker broadways.",
    actors: [
      { seat: "SB", label: "Opens" },
      { seat: "BB", label: "Hero" },
    ],
  },
  {
    id: "3m-open-a9s",
    tableSize: "three",
    pack: "100bb Cash",
    title: "Stay on the front foot with suited aces",
    copy: "Three-handed play rewards button aggression, and suited aces bring blockers plus flush potential.",
    heroHand: "A9s",
    heroSeat: "BTN",
    difficulty: "Core",
    xp: 18,
    facts: [
      { label: "Hero Seat", value: "BTN" },
      { label: "Pot Type", value: "Unopened" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Open 2.3x", "Open Jam"],
    correctAction: "Open 2.3x",
    explanation: "A9s has enough strength and blocker leverage to be a straightforward button open.",
    actors: [{ seat: "BTN", label: "Hero" }],
  },
  {
    id: "3m-bb-3bet-ajo",
    tableSize: "three",
    pack: "100bb Cash",
    title: "Upgrade to the aggressive defend",
    copy: "Button opens and this hand is strong enough to extract value and deny equity with a 3-bet.",
    heroHand: "AJo",
    heroSeat: "BB",
    difficulty: "Sharp",
    xp: 24,
    facts: [
      { label: "Hero Seat", value: "BB" },
      { label: "Villain", value: "BTN opens 2.3x" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Call", "3-bet to 10.5bb"],
    correctAction: "3-bet to 10.5bb",
    explanation: "AJo gains by taking initiative against the wide button range rather than passively realizing offsuit equity.",
    actors: [
      { seat: "BTN", label: "Opens" },
      { seat: "BB", label: "Hero" },
    ],
  },
  {
    id: "3m-sb-open-t8s",
    tableSize: "three",
    pack: "100bb Cash",
    title: "Pressure the big blind after a fold",
    copy: "Once the button folds, suited connectors become excellent candidates to attack from the small blind.",
    heroHand: "T8s",
    heroSeat: "SB",
    difficulty: "Core",
    xp: 18,
    facts: [
      { label: "Hero Seat", value: "SB" },
      { label: "Pot Type", value: "Folded to SB" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Open 3x", "Open Jam"],
    correctAction: "Open 3x",
    explanation: "T8s has strong playability and benefits from the initiative advantage blind versus blind.",
    actors: [{ seat: "SB", label: "Hero" }],
  },
  {
    id: "3m-bb-3bet-a4s",
    tableSize: "three",
    pack: "100bb Cash",
    title: "Leverage suited wheel aces blind versus blind",
    copy: "Small blind opens and you can use the ace blocker plus suited connectivity to fight back aggressively.",
    heroHand: "A4s",
    heroSeat: "BB",
    difficulty: "Sharp",
    xp: 24,
    facts: [
      { label: "Hero Seat", value: "BB" },
      { label: "Villain", value: "SB opens 3x" },
      { label: "Stacks", value: "100bb" },
    ],
    options: ["Fold", "Call", "3-bet to 12bb"],
    correctAction: "3-bet to 12bb",
    explanation: "A4s is a classic suited wheel ace that leverages blockers and retains equity when called.",
    actors: [
      { seat: "SB", label: "Opens" },
      { seat: "BB", label: "Hero" },
    ],
  },
]);
